#! /usr/bin/env python

# So, in the above Python script, we are generating a very simple logic:
# If there's no obstacle closer than 1 meter in front of the robot: move forward
# If there's an obstacle closer than 1 meter in front of the robot: turn left
# If there's an obstacle closer than 1 meter at the right side of the robot: turn left
# If there's an obstacle closer than 1 meter at the left side of the robot: turn right


import rospy
import math

from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist

def callback(msg):

	if msg.ranges[639] and msg.ranges[0] > 0.01 :
            move.linear.x = 0.0
	    move.angular.z = 0.0
        
  	pub.publish(move)

rospy.init_node("move_risc")
sub = rospy.Subscriber('/scan', LaserScan, callback)
pub = rospy.Publisher('cmd_vel_mux/input/teleop', Twist, queue_size = 1)
move = Twist()

rospy.spin()
